### ISSUE TITLE
script requires additional configuration with MacOS 10.12

### ISSUE THREAD

**Issue by deesto** [msimerson/ssh-agent#2]
FYI: OS X 10.12 (Sierra) changed the way it uses SSL and the OS X keychain, which includes SSH, and seems to have broken this script. I can confirm that it was working perfectly until OS X 10.12. Now, your key is still loaded initially via this script, but the agent does not pass the loaded key and pass phrase along to remote systems, which makes the agent somewhat useless.

Some discussion about this here, including links to other issues and possible solutions: https://github.com/lionheart/openradar-mirror/issues/15361

**Comment by msimerson** [comment]
Your title is misleading. The script is not broken and it still works just fine on 10.12. 

What seems (based on that link) is that usage of `ssh-add -K` appears to have changed. The reason that hasn't affected me is because I don't ever use `ssh-add -K`. My oldest private keys aren't passphrase protected and are thus loaded up automatically. The keys I've generated and use in the past decade all have passphrases and I manually load them. I don't reboot often so it's not much of an inconvenience.

I also keep my SSH password stored in a separate encrypted store. I do consulting work so my SSH public key is installed on literally thousands of machines all over the world. I am thus cautious to assure that neither factor (physical possession of the private key and the secret passphrase) is "out there" where it can be compromised.

**Comment by deesto** [comment]
Hi @msimerson,

> Your title is misleading. The script is not broken and it still works just fine on 10.12.

Unfortunately, it doesn't work for me. Clearly, our use of SSH (and systems on which we use them) differs, and in my case, the script as it now stands no longer works. I thought the 'title' implied the fact that a change in the OS was responsible, but perhaps that isn't clear enough. Feel free to change it.

> What seems (based on that link) is that usage of `ssh-add -K` appears to have changed.

Indeed, but other options and things have changed as well, including the need to use the `-A` option with the SSH client, and the addition of an SSH client config option (`AddKeysToAgent yes`), in order to use the script -- again, with the caveat of _in my use case_, juxtaposed against your usage, for which this may not be necessary.

I began the post with "FYI" as I thought you might find the included details useful; if not, please close and discard the comment.

**Comment by msimerson** [comment]
I do appreciate you posting it here. It is likely to help those who store their passphrase in the MacOS Keychain.

I'll leave this open for a while, for others who may find it useful.
